<<<<<<< HEAD
# Generated by Django 4.2.1 on 2023-05-31 15:35
=======
# Generated by Django 4.2.1 on 2023-05-31 16:13
>>>>>>> a6838df4650cae82d7537990fe940fc4cf5b378c

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
